spring.application.name=doctor-appointment


spring.datasource.url = jdbc:mysql://localhost:3306/doctor_appointment_system
spring.datasource.username = root
spring.datasource.password = Gulshan@6758
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql=true


deploy.env = development;
frontEndUrl = http://localhost:8080

jwt.secret=${JWT_SECRET}


project.images = D:/doctor-appointment/images